server:
  port: 8080
spring:
  profiles:
    active:
    - test
  jpa:
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
default:
 sender: g2glite.naoresponda@gmail.com
 recipent: g2glite.naoresponda@gmail.com
jwt: 
  secret: SecureSequenceforYourVersionofThisAPPg2glite20
  expiration: 86400000
  
aws:
  access_key_id: 
  secret_access_key: 
s3:
  bucket: g2glite
  region: sa-east-1
img:
  prefix:
    client:
      profile: cp
  profile:
    size: 200
  