server:
  port: 8080
spring:
  profiles:
    active:
    - test
  jpa:
    open-in-view: true
default:
 sender: alexandrerosseto@gmail.com
 recipent: alexandrerosseto@gmail.com
jwt: 
  secret: CharactersSequenceToAssignToken
  expiration: 60000